services:
  - type: web
    name: django-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn django_project.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: django_project.settings
